<?php

/**
 * @file
 * Loggly HTTP module.
 */

define('LOGGLY_HTTP_LOG', 'http://logs-01.loggly.com/inputs/');

/**
 * Implements hook_boot().
 *
 * Runs even for cached pages.
 */
function loggly_http_boot() {
  drupal_register_shutdown_function('loggly_http_shutdown');
}

/**
 * Runs on shutdown to clean up and display developer information.
 *
 * devel_boot() registers this function as a shutdown function.
 */
function loggly_http_shutdown() {
  if (!$events = loggly_http_get_registered_events()) {
    return;
  }

  // Send events to loggly.
  foreach ($events as $event) {
    $loggly_endpoint = variable_get('loggly_http_url');

    $options = array(
      'method' => 'POST',
      'data' => drupal_json_encode($event),
    );

    // Send data to Loggly.
    $response = drupal_http_request($loggly_endpoint, $options);
  }
}

function loggly_http_register_event(array $event = array()) {
  $events = &drupal_static('loggly_http_events', array());
  $events[] = $event;
}

function loggly_http_get_registered_events() {
  $events = &drupal_static('loggly_http_events', array());
  return $events;
}

/**
 * Implements hook_menu().
 */
function loggly_http_menu() {
  $items = array();

  $items['admin/config/services/loggly-http-client'] = array(
    'type' => MENU_NORMAL_ITEM,
    'title' => 'Loggly HTTP Client',
    'description' => 'Administer Loggly Client settings.',
    'access arguments' => array('administer loggly http client'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('loggly_http_admin_settings'),
    'file' => 'loggly_http.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function loggly_http_permission() {
  $permissions = array();

  $permissions['administer loggly http client'] = array(
    'title' => t('Administer Loggly HTTP client'),
  );

  return $permissions;
}

/**
 * Implements hook_watchdog().
 *
 * HTTP POST JSON Object as a single event.
 */
function loggly_http_watchdog(array $log_entry) {
  if (!variable_get('loggly_http_enabled') || !variable_get('loggly_http_url')) {
    return;
  }


  if ($log_entry['severity'] > variable_get('loggly_http_severity_level')) {
    // Severity level is above the ones we want to log.
    return;
  }

  $event = array(
    'timestamp' => $log_entry['timestamp'],
    'type' => $log_entry['type'],
    'ip' => $log_entry['ip'],
    'request_uri' => $log_entry['request_uri'],
    'referer' => $log_entry['referer'],
    'uid' => $log_entry['uid'],
    'link' => strip_tags($log_entry['link']),
    'message' => empty($log_entry['variables']) ? $log_entry['message'] : strtr($log_entry['message'], $log_entry['variables']),
  );

    if ($log_entry['severity'] >= WATCHDOG_CRITICAL) {
      // Capture the functions stack. We can't send the entire backtrace, as
      // it might clog the memory.
      $debug_backtrace = array();
      foreach (debug_backtrace() as $debug) {
        $debug_backtrace[] = $debug['function'];

      }
      $event += array(
        'debug_backtrace' => $debug_backtrace,
      );
    }


  loggly_http_register_event($event);
}
